### ISSUE TITLE
Spelling errors create cursorline gaps

### ISSUE THREAD

**Issue by seandewar** [bluz71/vim-moonfly-colors#13]
Seems to happen in both TUI and GUI nvim.

Especially apparent with nvim-treesitter's `highlight`s enabled, which disables the regular `syntax`-based highlighting, using `extmark`s instead:

![image](https://user-images.githubusercontent.com/6256228/111352415-0d2c3600-867c-11eb-8744-b1c4701904c3.png)

Usually, with `:syntax on`, code is ignored by the spell checker, which makes this less apparent outside of comments.
It seems that removing the `ctermbg` and `guibg` attributes from the `:highlight` fixes the issue:

![image](https://user-images.githubusercontent.com/6256228/111352383-043b6480-867c-11eb-85b4-140ef0f88a1d.png)

**Comment by bluz71** [comment]
@seandewar,

Issue should now be resolved.

Thanks for the bug report.

Best regards.

**Comment by seandewar** [comment]
No problem!

Thank you for making this awesome color scheme!
Been happily using it for nearly 6 months now. :)

**Comment by toofar** [comment]
Is there anyway I can revert back to the old behavior locally? I realize that the brightness is the vim default but wow is it bright. (Or otherwise change the bad spelling styling, I don't customize vim much, I just updated my plugins for the first time in a while. Then bisected to this change.)
![image](https://user-images.githubusercontent.com/7419144/135230661-d38b6b96-b3cd-416e-8fa7-23f8b2954ed0.png)

**Comment by bluz71** [comment]
I believe that is likely a Vim bug when undercurl is set, I don't see that issue with Neovim.

I strongly recommend you set `let g:moonflyUndercurls = 0`. The problem should go away.

**Comment by toofar** [comment]
Hmmm, I reduced my ~/.vimrc to just
```
let g:moonflyUndercurls = 0
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'bluz71/vim-moonfly-colors'
call vundle#end()
colorscheme moonfly
set spell
```
And I still see the same pink in both vim and nvim. (My nvim init.vim just sources my vimrc)

**Comment by bluz71** [comment]
Which terminal program? That could well be having an effect.

I see the pink issue only with Vim in Alacritty when `g:moonflyUndercurls` is set.

**Comment by bluz71** [comment]
Can you print the value of `:hi SpellBad`.

**Comment by toofar** [comment]
> :hi SpellBad                                                  

    SpellBad       xxx term=reverse cterm=underline ctermfg=1 ctermbg=9
                   gui=underline guifg=#ff5454 guisp=#ff5454

I'm using urxvt (debian). I'm building alacritty now.

**Comment by bluz71** [comment]
Your `SpellBad` is what I expect (it is correct, no undercurls).

Hopefully your terminal is a factor. Let me know. Currently I can't reproduce the issue once I disable undercurls. I do not see this issue in alacritty, GNOME Terminal nor xterm (once `g:moonflyUndercurls` is disabled).

That has me thinking, I probably should not make undercurls the default. I will think on that.

**Comment by toofar** [comment]
alacritty looks even worse, oh no

![image](https://user-images.githubusercontent.com/7419144/135238108-d051fe8c-f675-4e50-b87a-9a84885da8b9.png)

I realised my terminal colorscheme from ~/.Xdefaults might affect it so I emptied that and it turned into red for urxvt and didn't change for alacritty

![image](https://user-images.githubusercontent.com/7419144/135238359-ad829e4a-7cd1-4971-8b11-1b0584e23f67.png)

I'm assuming the `ctermbg=9` means it is whatever is defining that that is doing it? I'm not sure where that could be coming from at this point, I'll have another look through my dotfiles tomorrow but there isn't much there.

(btw I honestly didn't remember installing this theme but while I'm not sure how I found it my dotfiles say I've been using is since 2017!)

**Comment by bluz71** [comment]
Try adding, set termguicolors to your vimrc.

I just remembered I stopped using cterm a long time ago. That could be having an effect.

**Comment by bluz71** [comment]
I think I can partially revert this treesitter fix, just for cterm. More testing at my end.

If you don’t have time, just leave it with me. I will explore on my own. I do want to fix this for you.

**Comment by toofar** [comment]
Telling it to use gui color definitely changes it. But now it doesn't have any colors. The docs say that if you get a colorless UI you need to read `:he xterm-true-color` so maybe I'm missing something else to to make that work.

![image](https://user-images.githubusercontent.com/7419144/135242211-02b92f53-75d7-4d2f-a715-68da6bab47dc.png)

**Comment by bluz71** [comment]
What’s the value of $TERM?
I suggest setting it to xterm-256color if using Alacritty.

**Comment by toofar** [comment]
That does restore color in alacritty. It has no effect in urxvt though. I don't particularly like setting TERM to something false, but that might just be because urxvt gets a bit weird when you do that. Apparently urxvt doesn't support true color ... and there is a patch somewhere.

![image](https://user-images.githubusercontent.com/7419144/135244693-98b66e04-9761-45db-a4c9-a23bb5ca2653.png)

**Comment by bluz71** [comment]
I think I have enough leads to go on now.

I will try and balance the competing interests of this issue, that being the original and yours.

I suggest locking your moonfly version to the last good one, until I sort this out. Give me a day or so, I should be able to figure a solution.

Lastly, you are a Vim user, not Neovim, correct?

**Comment by toofar** [comment]
Yes, vim. And thank you for caring.

**Comment by bluz71** [comment]
Hello @toofar,

I was able to repeat your issue with Vim and the base `cterm` version of moonfly.

I have just committed a fix for your issue, whilst also keeping the fix for the original issue in this issue. Should be a win - win for all.

Sorry for the breakage, but hopefully you should be good to go now.

Peace.

**Comment by toofar** [comment]
Looks good to me! It looks the same as I am used to as far as I can tell. Well it changes the color of the little "no file here" tildes (they are darker now) but I don't care about that.
Thank you again!
![image](https://user-images.githubusercontent.com/7419144/135383799-7b2aab03-668b-4143-b3b2-916711258be5.png)

**Comment by bluz71** [comment]
The tilde change is a deliberate (recent) change, among others (such as popup selection color). My colorschemes are always evolving.

Thankfully your issue is now fixed, which pleases me.

Best regards.
